### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by tremby** [duxiaofeng-github/typescript-debounce-decorator#1]
This debounce implementation always invokes the function with the arguments as *first* given, one debounce interval after the *first* call.

Any calls during the timeout period are totally discarded, and the eventual invocation is not delayed longer.

I would have expected any calls during the timeout period to *restart* the timer and discard any *earlier* arguments, and the invocation should the timer run out would use the arguments from the *latest* call. This is what I'm used to in debounce implementations.

**Comment by tvkit** [comment]
@tremby using for text input, and noticed similar behavior where data is lost on rapid, sequential input.  But when specifying the `leading` option to false, all the data is processed.

**Comment by tremby** [comment]
That doesn't sound right either. The whole point of debouncing is to *not* run your code every time, so if you're seeing all calls actually run something is wrong.

What I expect you mean is that when you switch that option to false, the latest call *is* happening and for your purposes this is what you want. (Like input on a text field.)

**Comment by duxiaofeng-github** [comment]
https://github.com/duxiaofeng-github/typescript-debounce-decorator/blob/be06eb87fe17a086118287af2872433a4d6e63a4/test.ts#L121

there is some unit test case in above link. The decorator should behave normally as these test passed.

**Comment by bennypowers** [comment]
I lost about half a day because I didn't realize this package assumes `leading: true` as the default value. Most debounce implementations are the opposite. 

I suggest a breaking change which makes `leading` opt-in

Thanks for publishing this decorator :D

**Comment by benkrejci** [comment]
I very much appreciate the decorator, but agree with @bennypowers this was really confusing to me. The default behavior for all other debounce utilities I've used (and what makes the most sense to me for an overwhelming majority of use-cases) is for leading to be false by default

**Comment by duxiaofeng-github** [comment]
@bennypowers @benkrejci now its leading option is default to false.

it's a breaking change, it may affect your code which was using it.

**Comment by bennypowers** [comment]
Thank you ❤️

**Comment by benkrejci** [comment]
🎉🥳 thank you!
